### ISSUE TITLE
Fails to build on recent rust versions

### ISSUE THREAD

**Issue by micwoj92** [danielzgtg/new-planner#1]
Features option_unwrap_none and option_expect_none were not stabilized and removed in mid of 2021.

**Comment by danielzgtg** [comment]
Thank you @micwoj92 for reporting this bug!

Wow! I'm happy that people are actually interested in my repositories. This one, even I forgot what it was for until I did `cargo run`. I wrote this project during a phase when I was struggling to get time management sorted out, and this method was one of the things I experimented with.
